### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by wwjwy** [HiLab-git/WSL4MIS#4]
Dear Luo,

I divided the content into two categories, background and dog.  According to your previous help, the format of my dataset is as follows, are they correct?
![1](https://user-images.githubusercontent.com/66406998/119621253-7973a480-be38-11eb-981b-eacd81f329ab.jpg)
![1](https://user-images.githubusercontent.com/66406998/119621268-7d9fc200-be38-11eb-9297-5a43c8ef2e61.png)

Thanks!

**Comment by Luoxd1996** [comment]
Hi,
Yes, it's right.
Best,
Xiangde.

**Comment by wwjwy** [comment]
Thank you for your help!
