### ISSUE TITLE
pre-process data

### ISSUE THREAD

**Issue by SonwYang** [HiLab-git/WSL4MIS#5]
Hi!For some reason, I can't download dataset. Can you provide me the pre-processed data? Thank you!!!

**Comment by Luoxd1996** [comment]
Hi,
Sure, you can send me an email, and then I will send you the processed data.
Best,
Xiangde.

**Comment by SonwYang** [comment]
OK!Here is my ***@***.*** Thank you very much!




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年7月1日(星期四) 下午3:00
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Luoxd1996/WSL4MIS] pre-process data (#5)





 
Hi,
 Sure, you can send me an email, and then I will send you the processed data.
 Best,
 Xiangde.

**Comment by Luoxd1996** [comment]
Hi, 
Sorry, I don't know what is your email number, please email me.
Best,
Xiangde.

**Comment by SonwYang** [comment]
OK! I have send you email. please check out.
