### ISSUE TITLE
RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 1. Got 26 and 27 in dimension 3 at /opt/conda/conda-bld/pytorch_1579022034529/work/aten/src/THC/generic/THCTensorMath.cu:71

### ISSUE THREAD

**Issue by huanqingxu** [HiLab-git/WSL4MIS#7]
ile "/media/lab549/CE56C94660FE3E83/semantic_segmentation_xhq/code_xhq/WSL4MIS-main/code/networks/unet.py", line 70, in forward
    x = torch.cat([x2, x1], dim=1)
RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 1. Got 26 and 27 in dimension 3 at /opt/conda/conda-bld/pytorch_1579022034529/work/aten/src/THC/generic/THCTensorMath.cu:71

**Comment by Luoxd1996** [comment]
what？

**Comment by huanqingxu** [comment]
罗博，我的私有数据出现问题，所以导致报错，不好意思给你带来的打扰，现在处理好了就没有问题了，非常感谢！



---Original---
From: ***@***.***&gt;
Date: Sun, Nov 28, 2021 09:21 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [HiLab-git/WSL4MIS] RuntimeError: invalid argument 0: Sizes oftensors must match except in dimension 1. Got 26 and 27 in dimension 3 at/opt/conda/conda-bld/pytorch_1579022034529/work/aten/src/THC/generic/THCTensorMath.cu:71(Issue #7)




 
what？
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
